### ISSUE TITLE
Configuring proxy for selenium-server

### ISSUE THREAD

**Issue by jerri** [shiningpanda/selenose#2]
I am trying to use selenose to test a website which I can only reach via a proxy. Right now it seems you can't give the -Dhttp... properties to the invocation of selenium-server. Do you have other ideas how to configure selenium-server to use a proxy?

**Comment by jerri** [comment]
Sorry, not enough information.  I am using selenose under debian. It seems though, that the http_proxy-Environment-Variable does work. So maybe this is no issue. :)

**Comment by omansion** [comment]
For now it's not possible to add some -D options on the command line launching the server.

If http_proxy-Environment-Variable can do the job while I implement this it would be great!
