### ISSUE TITLE
How to use multiple drivers at once

### ISSUE THREAD

**Issue by timc3** [shiningpanda/selenose#5]
In your documentation/blog it says that you can pass  --selenium-driver to test against a particular driver setup.

What if I want to test against multiple drivers one after the other. And what if I want the output of all the results in to one XML?

**Comment by omansion** [comment]
It's currently not possible, but you should have a look on [tox](http://tox.readthedocs.org/en/latest/) or Jenkins' multi-configuration projects (full sample [here](https://www.shiningpanda-ci.com/docs/tutorials/selenium/job.html)), they allow to run the same build with different input parameters (the browser in our case).

**Comment by timc3** [comment]
Yes, I think I will look in the axis support in Jenkins.

Thanks for the help.
